//
//  geopackage-ios.h
//  geopackage-ios
//
//  Created by Brian Osborn on 9/1/15.
//  Copyright (c) 2015 NGA. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for geopackage-ios.
FOUNDATION_EXPORT double geopackage_iosVersionNumber;

//! Project version string for geopackage-ios.
FOUNDATION_EXPORT const unsigned char geopackage_iosVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <geopackage_ios/PublicHeader.h>

#import <geopackage_ios/GPKGBoundingBox.h>
#import <geopackage_ios/GPKGDateTimeUtils.h>
#import <geopackage_ios/GPKGGeoPackage.h>
#import <geopackage_ios/GPKGGeoPackageCache.h>
#import <geopackage_ios/GPKGGeoPackageConstants.h>
#import <geopackage_ios/GPKGUtils.h>
#import <geopackage_ios/geopackage_ios.h>
#import <geopackage_ios/GPKGAttributesColumn.h>
#import <geopackage_ios/GPKGAttributesDao.h>
#import <geopackage_ios/GPKGAttributesRow.h>
#import <geopackage_ios/GPKGAttributesTable.h>
#import <geopackage_ios/GPKGAttributesTableReader.h>
#import <geopackage_ios/GPKGContents.h>
#import <geopackage_ios/GPKGContentsDao.h>
#import <geopackage_ios/GPKGContentsDataTypes.h>
#import <geopackage_ios/GPKGSpatialReferenceSystem.h>
#import <geopackage_ios/GPKGSpatialReferenceSystemDao.h>
#import <geopackage_ios/GPKGAlterTable.h>
#import <geopackage_ios/GPKGConnection.h>
#import <geopackage_ios/GPKGConnectionFunction.h>
#import <geopackage_ios/GPKGDataTypes.h>
#import <geopackage_ios/GPKGFeatureIndexer.h>
#import <geopackage_ios/GPKGGeoPackageTableCreator.h>
#import <geopackage_ios/GPKGMappedColumn.h>
#import <geopackage_ios/GPKGResultSet.h>
#import <geopackage_ios/GPKGSqlLiteQueryBuilder.h>
#import <geopackage_ios/GPKGSqlUtils.h>
#import <geopackage_ios/GPKGTableCreator.h>
#import <geopackage_ios/GPKGTableMapping.h>
#import <geopackage_ios/GPKGBaseDao.h>
#import <geopackage_ios/GPKGColumnValue.h>
#import <geopackage_ios/GPKGColumnValues.h>
#import <geopackage_ios/GPKGSQLiteMaster.h>
#import <geopackage_ios/GPKGSQLiteMasterColumns.h>
#import <geopackage_ios/GPKGSQLiteMasterQuery.h>
#import <geopackage_ios/GPKGSQLiteMasterTypes.h>
#import <geopackage_ios/GPKGGeoPackageMetadata.h>
#import <geopackage_ios/GPKGGeoPackageMetadataDao.h>
#import <geopackage_ios/GPKGGeoPackageMetadataTableCreator.h>
#import <geopackage_ios/GPKGGeometryMetadata.h>
#import <geopackage_ios/GPKGGeometryMetadataDao.h>
#import <geopackage_ios/GPKGMetadataDb.h>
#import <geopackage_ios/GPKGTableMetadata.h>
#import <geopackage_ios/GPKGTableMetadataDao.h>
#import <geopackage_ios/GPKGConnectionPool.h>
#import <geopackage_ios/GPKGDbConnection.h>
#import <geopackage_ios/GPKGSqliteConnection.h>
#import <geopackage_ios/GPKGColumnConstraints.h>
#import <geopackage_ios/GPKGConstraint.h>
#import <geopackage_ios/GPKGConstraintParser.h>
#import <geopackage_ios/GPKGConstraintTypes.h>
#import <geopackage_ios/GPKGRawConstraint.h>
#import <geopackage_ios/GPKGTableColumn.h>
#import <geopackage_ios/GPKGTableConstraints.h>
#import <geopackage_ios/GPKGTableInfo.h>
#import <geopackage_ios/GPKGUniqueConstraint.h>
#import <geopackage_ios/GPKGBaseExtension.h>
#import <geopackage_ios/GPKGCrsWktExtension.h>
#import <geopackage_ios/GPKGExtensions.h>
#import <geopackage_ios/GPKGExtensionsDao.h>
#import <geopackage_ios/GPKGFeatureIndexRTreeResults.h>
#import <geopackage_ios/GPKGExtensionManager.h>
#import <geopackage_ios/GPKGGeometryExtensions.h>
#import <geopackage_ios/GPKGMetadataExtension.h>
#import <geopackage_ios/GPKGNGAExtensions.h>
#import <geopackage_ios/GPKGRTreeIndexExtension.h>
#import <geopackage_ios/GPKGRTreeIndexTableDao.h>
#import <geopackage_ios/GPKGRTreeIndexTableRow.h>
#import <geopackage_ios/GPKGSchemaExtension.h>
#import <geopackage_ios/GPKGWebPExtension.h>
#import <geopackage_ios/GPKGZoomOtherExtension.h>
#import <geopackage_ios/GPKGContentsId.h>
#import <geopackage_ios/GPKGContentsIdDao.h>
#import <geopackage_ios/GPKGContentsIdExtension.h>
#import <geopackage_ios/GPKGCoverageData.h>
#import <geopackage_ios/GPKGCoverageDataAlgorithms.h>
#import <geopackage_ios/GPKGCoverageDataImage.h>
#import <geopackage_ios/GPKGCoverageDataPng.h>
#import <geopackage_ios/GPKGCoverageDataPngImage.h>
#import <geopackage_ios/GPKGCoverageDataRequest.h>
#import <geopackage_ios/GPKGCoverageDataResults.h>
#import <geopackage_ios/GPKGCoverageDataSourcePixel.h>
#import <geopackage_ios/GPKGCoverageDataTiff.h>
#import <geopackage_ios/GPKGCoverageDataTiffImage.h>
#import <geopackage_ios/GPKGCoverageDataTileMatrixResults.h>
#import <geopackage_ios/GPKGGriddedCoverage.h>
#import <geopackage_ios/GPKGGriddedCoverageDao.h>
#import <geopackage_ios/GPKGGriddedCoverageDataTypes.h>
#import <geopackage_ios/GPKGGriddedCoverageEncodingTypes.h>
#import <geopackage_ios/GPKGGriddedTile.h>
#import <geopackage_ios/GPKGGriddedTileDao.h>
#import <geopackage_ios/GPKGFeatureTableIndex.h>
#import <geopackage_ios/GPKGGeometryIndex.h>
#import <geopackage_ios/GPKGGeometryIndexDao.h>
#import <geopackage_ios/GPKGTableIndex.h>
#import <geopackage_ios/GPKGTableIndexDao.h>
#import <geopackage_ios/GPKGFeatureTileLink.h>
#import <geopackage_ios/GPKGFeatureTileLinkDao.h>
#import <geopackage_ios/GPKGFeatureTileTableLinker.h>
#import <geopackage_ios/GPKGPropertiesExtension.h>
#import <geopackage_ios/GPKGPropertiesManager.h>
#import <geopackage_ios/GPKGPropertyNames.h>
#import <geopackage_ios/GPKGExtendedRelation.h>
#import <geopackage_ios/GPKGExtendedRelationsDao.h>
#import <geopackage_ios/GPKGRelatedTablesExtension.h>
#import <geopackage_ios/GPKGRelationTypes.h>
#import <geopackage_ios/GPKGUserMappingDao.h>
#import <geopackage_ios/GPKGUserMappingRow.h>
#import <geopackage_ios/GPKGUserMappingTable.h>
#import <geopackage_ios/GPKGUserRelatedTable.h>
#import <geopackage_ios/GPKGDublinCoreMetadata.h>
#import <geopackage_ios/GPKGDublinCoreTypes.h>
#import <geopackage_ios/GPKGMediaDao.h>
#import <geopackage_ios/GPKGMediaRow.h>
#import <geopackage_ios/GPKGMediaTable.h>
#import <geopackage_ios/GPKGSimpleAttributesDao.h>
#import <geopackage_ios/GPKGSimpleAttributesRow.h>
#import <geopackage_ios/GPKGSimpleAttributesTable.h>
#import <geopackage_ios/GPKGTileScaling.h>
#import <geopackage_ios/GPKGTileScalingDao.h>
#import <geopackage_ios/GPKGTileScalingTypes.h>
#import <geopackage_ios/GPKGTileTableScaling.h>
#import <geopackage_ios/GPKGFeatureStyle.h>
#import <geopackage_ios/GPKGFeatureStyleExtension.h>
#import <geopackage_ios/GPKGFeatureStyles.h>
#import <geopackage_ios/GPKGFeatureTableStyles.h>
#import <geopackage_ios/GPKGIconCache.h>
#import <geopackage_ios/GPKGIconDao.h>
#import <geopackage_ios/GPKGIconRow.h>
#import <geopackage_ios/GPKGIconTable.h>
#import <geopackage_ios/GPKGIcons.h>
#import <geopackage_ios/GPKGStyleDao.h>
#import <geopackage_ios/GPKGStyleMappingDao.h>
#import <geopackage_ios/GPKGStyleMappingRow.h>
#import <geopackage_ios/GPKGStyleMappingTable.h>
#import <geopackage_ios/GPKGStyleRow.h>
#import <geopackage_ios/GPKGStyleTable.h>
#import <geopackage_ios/GPKGStyles.h>
#import <geopackage_ios/GPKGGeoPackageFactory.h>
#import <geopackage_ios/GPKGGeoPackageManager.h>
#import <geopackage_ios/GPKGSessionTaskData.h>
#import <geopackage_ios/GPKGFeatureGenerator.h>
#import <geopackage_ios/GPKGOAPIFeatureGenerator.h>
#import <geopackage_ios/GPKGGeometryColumns.h>
#import <geopackage_ios/GPKGGeometryColumnsDao.h>
#import <geopackage_ios/GPKGFeatureIndexFeatureResults.h>
#import <geopackage_ios/GPKGFeatureIndexGeoPackageResults.h>
#import <geopackage_ios/GPKGFeatureIndexListResults.h>
#import <geopackage_ios/GPKGFeatureIndexManager.h>
#import <geopackage_ios/GPKGFeatureIndexMetadataResults.h>
#import <geopackage_ios/GPKGFeatureIndexResultSetResults.h>
#import <geopackage_ios/GPKGFeatureIndexResults.h>
#import <geopackage_ios/GPKGFeatureIndexTypes.h>
#import <geopackage_ios/GPKGMultipleFeatureIndexResults.h>
#import <geopackage_ios/GPKGFeatureCache.h>
#import <geopackage_ios/GPKGFeatureCacheTables.h>
#import <geopackage_ios/GPKGFeatureColumn.h>
#import <geopackage_ios/GPKGFeatureDao.h>
#import <geopackage_ios/GPKGFeatureRow.h>
#import <geopackage_ios/GPKGFeatureTable.h>
#import <geopackage_ios/GPKGFeatureTableReader.h>
#import <geopackage_ios/GPKGManualFeatureQuery.h>
#import <geopackage_ios/GPKGManualFeatureQueryResults.h>
#import <geopackage_ios/GPKGGeometryData.h>
#import <geopackage_ios/GPKGGeometryUtils.h>
#import <geopackage_ios/GPKGFeatureShape.h>
#import <geopackage_ios/GPKGFeatureShapes.h>
#import <geopackage_ios/GPKGLocationBoundingBox.h>
#import <geopackage_ios/GPKGMapPoint.h>
#import <geopackage_ios/GPKGMapPointInitializer.h>
#import <geopackage_ios/GPKGMapPointOptions.h>
#import <geopackage_ios/GPKGMapShape.h>
#import <geopackage_ios/GPKGMapShapeConverter.h>
#import <geopackage_ios/GPKGMapShapePoints.h>
#import <geopackage_ios/GPKGMapShapeTypes.h>
#import <geopackage_ios/GPKGMultiPoint.h>
#import <geopackage_ios/GPKGMultiPolygon.h>
#import <geopackage_ios/GPKGMultiPolygonPoints.h>
#import <geopackage_ios/GPKGMultiPolyline.h>
#import <geopackage_ios/GPKGMultiPolylinePoints.h>
#import <geopackage_ios/GPKGPolygon.h>
#import <geopackage_ios/GPKGPolygonHolePoints.h>
#import <geopackage_ios/GPKGPolygonOptions.h>
#import <geopackage_ios/GPKGPolygonOrientations.h>
#import <geopackage_ios/GPKGPolygonPoints.h>
#import <geopackage_ios/GPKGPolyline.h>
#import <geopackage_ios/GPKGPolylineOptions.h>
#import <geopackage_ios/GPKGPolylinePoints.h>
#import <geopackage_ios/GPKGShapePoints.h>
#import <geopackage_ios/GPKGShapeWithChildrenPoints.h>
#import <geopackage_ios/GPKGCompressFormats.h>
#import <geopackage_ios/GPKGIOUtils.h>
#import <geopackage_ios/GPKGImageConverter.h>
#import <geopackage_ios/GPKGProgress.h>
#import <geopackage_ios/GPKGMapTolerance.h>
#import <geopackage_ios/GPKGMapUtils.h>
#import <geopackage_ios/GPKGFeatureInfoBuilder.h>
#import <geopackage_ios/GPKGStyleCache.h>
#import <geopackage_ios/GPKGStyleUtils.h>
#import <geopackage_ios/GPKGMetadata.h>
#import <geopackage_ios/GPKGMetadataDao.h>
#import <geopackage_ios/GPKGMetadataScope.h>
#import <geopackage_ios/GPKGMetadataReference.h>
#import <geopackage_ios/GPKGMetadataReferenceDao.h>
#import <geopackage_ios/GPKGProperties.h>
#import <geopackage_ios/GPKGPropertyConstants.h>
#import <geopackage_ios/GPKGDataColumns.h>
#import <geopackage_ios/GPKGDataColumnsDao.h>
#import <geopackage_ios/GPKGDataColumnConstraints.h>
#import <geopackage_ios/GPKGDataColumnConstraintsDao.h>
#import <geopackage_ios/GPKGColor.h>
#import <geopackage_ios/GPKGColorConstants.h>
#import <geopackage_ios/GPKGColorUtils.h>
#import <geopackage_ios/GPKGTileBoundingBoxUtils.h>
#import <geopackage_ios/GPKGTileGenerator.h>
#import <geopackage_ios/GPKGTileGrid.h>
#import <geopackage_ios/GPKGTileUtils.h>
#import <geopackage_ios/GPKGUrlTileGenerator.h>
#import <geopackage_ios/GPKGCustomFeaturesTile.h>
#import <geopackage_ios/GPKGFeatureTileContext.h>
#import <geopackage_ios/GPKGFeatureTileGenerator.h>
#import <geopackage_ios/GPKGFeatureTilePointIcon.h>
#import <geopackage_ios/GPKGFeatureTiles.h>
#import <geopackage_ios/GPKGNumberFeaturesTile.h>
#import <geopackage_ios/GPKGTileMatrix.h>
#import <geopackage_ios/GPKGTileMatrixDao.h>
#import <geopackage_ios/GPKGTileMatrixSet.h>
#import <geopackage_ios/GPKGTileMatrixSetDao.h>
#import <geopackage_ios/GPKGBoundedOverlay.h>
#import <geopackage_ios/GPKGCompositeOverlay.h>
#import <geopackage_ios/GPKGFeatureOverlay.h>
#import <geopackage_ios/GPKGFeatureOverlayQuery.h>
#import <geopackage_ios/GPKGFeatureRowData.h>
#import <geopackage_ios/GPKGFeatureTableData.h>
#import <geopackage_ios/GPKGGeoPackageOverlay.h>
#import <geopackage_ios/GPKGOverlayFactory.h>
#import <geopackage_ios/GPKGXYZOverlay.h>
#import <geopackage_ios/GPKGGeoPackageTile.h>
#import <geopackage_ios/GPKGGeoPackageTileRetriever.h>
#import <geopackage_ios/GPKGXYZTileRetriever.h>
#import <geopackage_ios/GPKGTileCreator.h>
#import <geopackage_ios/GPKGTileRetriever.h>
#import <geopackage_ios/GPKGTileColumn.h>
#import <geopackage_ios/GPKGTileDao.h>
#import <geopackage_ios/GPKGTileDaoUtils.h>
#import <geopackage_ios/GPKGTileRow.h>
#import <geopackage_ios/GPKGTileTable.h>
#import <geopackage_ios/GPKGTileTableReader.h>
#import <geopackage_ios/GPKGContentValues.h>
#import <geopackage_ios/GPKGUserColumn.h>
#import <geopackage_ios/GPKGUserDao.h>
#import <geopackage_ios/GPKGUserRow.h>
#import <geopackage_ios/GPKGUserRowSync.h>
#import <geopackage_ios/GPKGUserTable.h>
#import <geopackage_ios/GPKGUserTableReader.h>
#import <geopackage_ios/GPKGUserCustomColumn.h>
#import <geopackage_ios/GPKGUserCustomDao.h>
#import <geopackage_ios/GPKGUserCustomRow.h>
#import <geopackage_ios/GPKGUserCustomTable.h>
#import <geopackage_ios/GPKGUserCustomTableReader.h>
#import <geopackage_ios/GPKGGeoPackageValidate.h>
#import <geopackage_ios/GPKGUserColumns.h>
#import <geopackage_ios/GPKGAttributesColumns.h>
#import <geopackage_ios/GPKGFeatureColumns.h>
#import <geopackage_ios/GPKGTileColumns.h>
#import <geopackage_ios/GPKGUserCustomColumns.h>
#import <geopackage_ios/GPKGFeatureIndexLocation.h>
#import <geopackage_ios/GPKGFeatureIndexerIdQuery.h>
#import <geopackage_ios/GPKGFeatureIndexerIdResultSet.h>
#import <geopackage_ios/GPKGFeaturePreview.h>
#import <geopackage_ios/GPKGUserTableMetadata.h>
#import <geopackage_ios/GPKGAttributesTableMetadata.h>
#import <geopackage_ios/GPKGConstraints.h>
#import <geopackage_ios/GPKGExtensionManagement.h>
#import <geopackage_ios/GPKGContentsIdTableCreator.h>
#import <geopackage_ios/GPKGGeometryIndexTableCreator.h>
#import <geopackage_ios/GPKGFeatureTileLinkTableCreator.h>
#import <geopackage_ios/GPKGTileScalingTableCreator.h>
#import <geopackage_ios/GPKGMediaTableMetadata.h>
#import <geopackage_ios/GPKGSimpleAttributesTableMetadata.h>
#import <geopackage_ios/GPKGFeatureTableMetadata.h>
#import <geopackage_ios/GPKGTileTableMetadata.h>
#import <geopackage_ios/GPKGNGATableCreator.h>
#import <geopackage_ios/GPKGTileReprojection.h>
#import <geopackage_ios/GPKGTileReprojectionZoom.h>
#import <geopackage_ios/GPKGTileReprojectionOptimize.h>
#import <geopackage_ios/GPKGPlatteCarreOptimize.h>
#import <geopackage_ios/GPKGWebMercatorOptimize.h>
#import <geopackage_ios/GPKGNetworkUtils.h>

